baseURL = 'https://spinningplates.net/'
languageCode = 'en-us'
title = 'spinning plates'
theme = 'PaperMod'

[params]
  [params.homeInfoParams]
    Title = 'Hello'
    Content = 'This is a blog.'

  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/fordy8k'
  [[params.socialIcons]]
    name = 'mastodon'
    url = 'https://infosec.exchange/@fordy8k'

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about hugo'
  url = '/about/'
  weight = -110
[[menu.main]]
  name = 'getting started'
  url = '/getting-started/'
  weight = -100